---
title: 'Class06: R function'
author: "Elisha"
date: "4/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Today we will focus on **R functions** but we will start with a bit of **file reading**.

```{r}
plot(1:10, type= "l", col = "blue")
```

```{r}
read.table("test1.txt", header = T, sep = ",")
```

```{r}
read.table("test2.txt", header = T, sep= "$")
```


```{r}
read.table("test3.txt", sep = "")
```



```{r}
read.csv("https://bioboot.github.io/bggn213_S19/class-material/test1.txt")
```

## Our first function
Add some numbers
```{r}
add <- function(x, y=1){
  #The body
  x + y
}
```
```{r}
add(c(1,2,4),5)
#add(1,2,3)
```
```{r}
rescale2 <- function(x, na.rm=T){
  rng <- range(x, na.rm =na.rm)
  (x-rng[1])/(rng[2]-rng[1])
}
```
```{r}
rescale(1:10)
```

```{r}
rescale2(c(1,3,NA,5,10), F)
```
```{r}
x <- c(1,3,NA,5,10)
  rng <- range(x, na.rm =T)
  rng
#  (x-rng[1])/(rng[2]-rng[1])

```


```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) { 
  if(na.rm) {
    rng <-range(x, na.rm=na.rm) } 
  else {
    rng <-range(x) }
    print("Hello") 
    answer <- (x - rng[1]) / (rng[2] - rng[1]) 
    print("is it me you are looking for?") 
  if(plot) {
    plot(answer, typ="b", lwd=4) } 
    print("I can see it in ...") }
```





















