---
title: "Class10"
author: "Elisha"
date: "5/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
wisc.df <- read.csv("WisconsinCancer.csv")
class(wisc.df)
table(wisc.df$diagnosis)
head(wisc.df)
# need a vector as input
y = colnames(wisc.df)
length(grep("_mean",y))
```
Select cols 3:32 and store as a matrix
```{r}
wisc.data <- wisc.df[,3:32]
row.names(wisc.data) <- wisc.df$id
diagnosis <-  wisc.df$diagnosis
```

```{r}
wisc.pr <- prcomp(wisc.data, scale = T)
summary(wisc.pr)
                
```

```{r}
biplot(wisc.pr)
```
```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,2], col = diagnosis, xlab = "PC1", ylab= "PC2")
```
```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,3], col = diagnosis, xlab = "PC1", ylab= "PC3")
```

```{r}
pr.var <- wisc.pr$sdev^2
head(pr.var)
```
```{r}
pve <- pr.var/sum(pr.var)
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

```{r}
barplot(pve, ylab = "Precent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```

```{r}
sort(abs((wisc.pr$rotation[,1])))
```

Section 3
```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
wisc.hclust <- hclust(data.dist, method = "complete")
plot(wisc.hclust)
abline (h=18, col= "red", lty=2)
```

```{r}
wisc.hclust(hclust(dist(scale(wisc.data))))
```

```{r}
wisc.hclust.cluters <- cutree(wisc.hclust, k=4)
table(wisc.hclust.cluters)
```

```{r}
table(wisc.hclust.cluters, diagnosis)
```

Section 5 ( combing method PCA + Cluster)
I am going to srat with the PCs that capture 
90% of the original cariance in the dataset(i.e. PC1 to PC7)

```{r}
wisc.pr.hclust <- hclust(dist(wisc.pr$x[,1:7]), method = "ward.D2")
```


```{r}
plot(wisc.pr.hclust)
grps <- cutree(wisc.pr.hclust, k=2)
table(grps)
table(grps, diagnosis)
```
```{r}
plot(wisc.pr$x[,1:2], col=grps)
```



```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,2], col = diagnosis)
```


```{r}
#url <- "new_samples.csv"
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc
```

```{r}
plot(wisc.pr$x[,1:2], col=diagnosis)
points(npc[,1], npc[,2], col="blue", pch=16, cex=3)
text(npc[,1], npc[,2], c(1,2), col="white")
```









